server:
  port: 8082

spring:
  application:
    name: user-service

  config:
    import:
      - "optional:classpath:eureka-client.yaml"
      - "optional:classpath:spring-doc.yaml"

  datasource:
    url: jdbc:postgresql://postgres:5432/mychoice_user
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  grpc:
    server:
      port: 9092
