server:
  port: 8083
spring:
  application:
    name: university-service
  config:
    import:
      - "optional:classpath:spring-doc.yaml"
      - "optional:classpath:grpc-client.yaml"
      - "optional:classpath:eureka-client.yaml"
  datasource:
    url: jdbc:postgresql://localhost:5432/mychoice_university
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  scheduling:
    rate: 30s
